version: '3.8'

services:
  web:
    build: .
    container_name: property_management_prod_web
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 property_management.wsgi:application
    ports:
      - "1914:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=False
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    networks:
      - prod_network

networks:
  prod_network:
    driver: bridge
